name: cyrsoxs-build

channels:
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - cxx-compiler
  - pybind11
  - cmake>3.8
  - make
  - hdf5
  - libconfig
  - cudatoolkit
  - openmp
  - cuda
  - cuda-nvcc
